FROM python:3.8

RUN mkdir /var/server
COPY server/ /var/server

WORKDIR /var/server
RUN pip install pipenv
#RUN pipenv run pip freeze > requirements.txt && RUN pip install -r requirements.txt
RUN pipenv install

EXPOSE 5000

CMD pipenv run python /var/server/main.py
